### ISSUE TITLE
September Update video in Capacity section

### ISSUE THREAD

**Issue by JoshLuedeman** [sqlballs/MicrosoftFabricPre-Con#175]
We need to add the link for the Tales from the Field September Fabric update to the capacity section of Module 2 (https://github.com/sqlballs/MicrosoftFabricPre-Con/blob/main/fabricoverview/02%20-%20Workspaces%2C%20User%20Security%2C%20Data%20Governance%2C%20and%20Data%20Integration.md#capacity) 

https://www.youtube.com/watch?v=TZnZob8B_Xk

**Comment by JoshLuedeman** [comment]
Nothing to report this week. Time set aside Wednesday and Friday

**Comment by JoshLuedeman** [comment]
Nothing to report until week of 10/23

**Comment by BuckWoody** [comment]
Bradley will assist

**Comment by sqlballs** [comment]
I will take this and update Module 1 with the Capacity Unit video from the Sept Fabric update
