### ISSUE TITLE
Change Module 2 & 1 Content

### ISSUE THREAD

**Issue by sqlballs** [sqlballs/MicrosoftFabricPre-Con#176]
change content as discussed during pre-con

**Comment by sqlballs** [comment]
Module 1

1.7 moves to pre-reqs and a (potential 1st thing check?)

2.1 Moves to Module 1 1.7


Module 2


Rename Module to Data Warehouse and Data Integration

2.1 Data Warehouse

2.2 Data Flows Gen 2

2.3 Data Pipelines 

Move exercises 2 - 8 to Module 2

Show me exercise will be a vastly simplified Data Flow Gen 2

Remove 2.4 security concepts


Module 3

Remove exercises 2 - 8 

Show me exercise - the power of notebooks, Pyodbc connection, beautiful soup scraping, Interact with Azure Open AI

Exercise 9 for short cut

Exercise 10 - 12 for lakehouse reporting

Then Data Wrangler

**Comment by neerajjhaveri** [comment]
Have completed the draft for Module 2 for review

**Comment by sqlballs** [comment]
Have completed Module 1, need to change module 3

**Comment by sqlballs** [comment]
Working on this 10/19 & finishing on 10/20

**Comment by sqlballs** [comment]
Removed exercises from Module 3 that were transfered to module 2

**Comment by sqlballs** [comment]
Meet and did work on Wed, another meeting on Friday

**Comment by sqlballs** [comment]
completed
