### ISSUE TITLE
Position videos before the exercises

### ISSUE THREAD

**Issue by sqlballs** [sqlballs/MicrosoftFabricPre-Con#181]
take the point of view of someone doing the course online, position the videos as examples

**Comment by BuckWoody** [comment]
No videos in Module 6

**Comment by JoshLuedeman** [comment]
Doing as part of Module 5 Rework

**Comment by sqlballs** [comment]
Module 1 complete, for capacity metrtics

**Comment by sqlballs** [comment]
Working on Module 3
