### ISSUE TITLE
Arrange modules for one-show, one do, one link

### ISSUE THREAD

**Issue by BuckWoody** [sqlballs/MicrosoftFabricPre-Con#182]
Each module should have a demo-show, a user-exercise (10-minutes max), and then concepts with links from there. The latter can be expanded or contracted as time dictates.

**Comment by BuckWoody** [comment]
Working this today

**Comment by BuckWoody** [comment]
Module 6 complete on Task

**Comment by sqlballs** [comment]
Module 1 complete

**Comment by JoshLuedeman** [comment]
Doing this as part of Module 5 rework

**Comment by sqlballs** [comment]
With this being a recording need to get a video put together for Module 3, will work on this Wednesday
