### ISSUE TITLE
Ensure latest info from Product is updated per Module

### ISSUE THREAD

**Issue by BuckWoody** [sqlballs/MicrosoftFabricPre-Con#183]
Review docs ruthlessly to ensure we have the latest screenshots, info, facts, and concepts

**Comment by BuckWoody** [comment]
All do this T-7

**Comment by JoshLuedeman** [comment]
Including in module 5 rework #187

**Comment by BuckWoody** [comment]
Added a comprehensive "Wha's New" link in 06

**Comment by BuckWoody** [comment]
Everyone add 

<li><a href="https://learn.microsoft.com/en-us/fabric/release-plan/> You can find the latest release information for each product/feature at this reference. </a></li>

To the "For Further Study" area of each module
