### ISSUE TITLE
Module 5 Content Re-work

### ISSUE THREAD

**Issue by JoshLuedeman** [sqlballs/MicrosoftFabricPre-Con#187]
Drop PowerBI Dev Project content
Convert completely to Fabric Streaming

**Comment by JoshLuedeman** [comment]
Nothing to report this week. Time set aside Wednesday and Friday

**Comment by JoshLuedeman** [comment]
Scratched out changed structure. Committing changes Friday

**Comment by JoshLuedeman** [comment]
Removed PowerBI content. Setting up for 3 sub-modules:

Working with Fabric and Azure Data Explorer
Working with Fabric and Streaming / Event Data
Working with Fabric and the Kusto Query Language (Kusto)

**Comment by JoshLuedeman** [comment]
Putting together sub module 1. REmoved PBI Content. Pulling together ADX content

**Comment by BuckWoody** [comment]
Will commit by T-6 because the github is public, so we want it to be clean.

**Comment by JoshLuedeman** [comment]
Updated in commit b996a5c
