### ISSUE TITLE
Update Module 4 Content

### ISSUE THREAD

**Issue by sqlballs** [sqlballs/MicrosoftFabricPre-Con#189]
Change modules to reflect

- Azure Data Studio
- SQL Server Management Studio
- Kusto Explorer Desktop
- Microsoft Excel
- Power BI Desktop

No hands all, all demo.

**Comment by dbabulldog-repo** [comment]
In the process of updating

**Comment by dbabulldog-repo** [comment]
Updated module 4. Closing out. Please file issues for defects.
