### ISSUE TITLE
Add Microsoft Fabric Roadmap to relevant sections

### ISSUE THREAD

**Issue by sqlballs** [sqlballs/MicrosoftFabricPre-Con#190]
Find your individual section and add it to the further learning links of your section.

https://learn.microsoft.com/en-us/fabric/release-plan/

**Comment by BuckWoody** [comment]
Should this just be at the top or bottom module of the course?

**Comment by JoshLuedeman** [comment]
Adding to rework of module 5

**Comment by sqlballs** [comment]
Module 1 complete

**Comment by sqlballs** [comment]
Add this to the Further learning links on each page

**Comment by BuckWoody** [comment]
Everyone add 

<li><a href="https://learn.microsoft.com/en-us/fabric/release-plan/> You can find the latest release information for each product/feature at this reference. </a></li>

To the "For Further Study" area of each module

**Comment by BuckWoody** [comment]
Assigned to @sqlballs

**Comment by JoshLuedeman** [comment]
added to module 5
