### ISSUE TITLE
Re-title Module 5

### ISSUE THREAD

**Issue by BuckWoody** [sqlballs/MicrosoftFabricPre-Con#192]
Brad/Josh, please comment on new title and content headings: 

<New Title> <Section Headings (i.e. what major topics are covered), ...n...n...>

**Comment by JoshLuedeman** [comment]
Done with commit b996a5c

05 - Real-Time Analytics with Microsoft Fabric

5.1 - Working with Azure Data Explorer in Microsoft Fabric
5.2 - Working with Fabric and Streaming / Event Data
5.3 - Working with Fabric and the Kusto Query Language (KQL)
