### ISSUE TITLE
Update Module 2, move old Module 4 to Module 2

### ISSUE THREAD

**Issue by sqlballs** [sqlballs/MicrosoftFabricPre-Con#198]
Module 4 will take this old content and move it to Module 2 titled Desktop Tools to use with Microsoft Fabric 

At a minimum,

Module 2 Desktop Tools to use with Microsoft Fabric 
Use the content that was previously Module 4 The Fabric Developer experience.
Add a section for the OneLake Data Explorer
Add a section for Storage Explorer
Add a link to the video on Storage Explorer

**Comment by JoshLuedeman** [comment]
Renamed Module 4 file

Left existing content there

OneLake File Explorer section is there

Added Storage Explorer section and link to TftF video aligned to Storage Explorer
