### ISSUE TITLE
Update Module 2 and rename it to Module 3

### ISSUE THREAD

**Issue by sqlballs** [sqlballs/MicrosoftFabricPre-Con#199]
Module 2 Data Warehouse and Data Integration  - change to  Module 3 Data Warehouse and Data Factory

Module 3 Data Warehouse and Data Factory 
Section 2.3 –  Update text to add information about time travel
Need to update it from Follow Steps 4-8 to follow steps 4 – 9.  This includes a new tutorial on Time Travel

**Comment by bradleyschacht** [comment]
@dbabulldog-repo and I have the updates committed to the BradS branch.

**Comment by bradleyschacht** [comment]
Changes complete.
