### ISSUE TITLE
Update and Rename Module 5 to Module 6

### ISSUE THREAD

**Issue by sqlballs** [sqlballs/MicrosoftFabricPre-Con#202]
Module 5 "Real-Time Analytics with Microsoft Fabric" will change to Module 6 "Real-Time Intelligence"

Module 6 "Real-Time Intelligence"  
All links that say Real-Time Analytics must be changed to Real-Time Intelligence
5.2 remove the individual exercise links and say follow steps 1 to 6, 7 is optional because it is clean up.
We need to add a section on Data Activator, Event house vs. KQL DB, and KQL Dashboard’s

**Comment by JoshLuedeman** [comment]
Changed all information in Module to refer to Real-Time Intelligence and not Analytics

**Comment by JoshLuedeman** [comment]
Rename complete of the module and changed the wording in for completing the tutorial in 5.2

**Comment by JoshLuedeman** [comment]
Updated TftF videos in content to be new versions of video that demonstrate verbiage and tutorial changes
